(ns pull-to-refresh.main
  (:require ["package:flutter/material.dart" :as m]
            ["dart:async" :as a]
            ["dart:core" :refer [Duration]]
            [pull-to-refresh.refresh :as refresh]))

(defn main []
  (m/runApp
   (m/MaterialApp
    .title "Welcome to Flutter"
    .theme (m/ThemeData .primarySwatch m.Colors/blue
                        .fontFamily "OyunQaganTig"
                        .brightness m.Brightness/dark)
    .home
    (m/Scaffold
     .appBar (m/AppBar
              .title (m/Text "Horizontal Pull To Refresh Example"))
    .body
    (refresh/horizontal-refresh
     {:on-refresh #(a.Future/delayed (Duration .seconds 2))
      :item-count 10
      :background-color (m/Color 0xFFf8f4fc)
      :reverse false}))
    ;;  (m/Center
    ;;            .child (m/Text "Text Text"
    ;;                           .style (m/TextStyle
    ;;                                   .color m.Colors/blue
    ;;                                   .fontSize 32.0))))
    .debugShowCheckedModeBanner false)))
